name: video_editor
version: 1.2.3
description: Video Editor allows trim, crop, rotate and scale video with a super
  flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffmpeg_kit_flutter_full_gpl: 4.5.1-LTS
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.2
  
  video_player:
    # path: packages/video_player
    git: 
      url: https://github.com/iEBuy-github/plugins-1
      ref: cf1ecafd21b0a7c014f8e7725e54e169b9af0138
      path: packages/video_player/video_player
  video_thumbnail: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
