name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
version: 2.0.2
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

publish_to: "none"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0
  # video_player_platform_interface: ^4.0.0
  video_player_platform_interface:
    git:
      url: https://github.com/iEBuy-github/video_editor
      ref: full
      path: packages/video_player_platform_interface

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^0.1.21

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
